# Generated by Django 2.2 on 2019-04-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_history_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='deleted_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='upload_time',
            field=models.DateTimeField(),
        ),
    ]
