# Generated by Django 2.2 on 2019-04-27 03:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190427_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 27, 3, 38, 45, 849103, tzinfo=utc)),
        ),
    ]
