# Generated by Django 2.2 on 2019-04-27 03:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190427_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='upload_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
